exclude = [
    ".*__pycache__",
    ".*egg-info",
    ".*tests",
    "api/src/transform/template.py",
    "docs",
    "venv",
]
source_roots = [
    "pkg",
]

[[modules]]
path = "pare"
depends_on = [
    { path = "pare.sdk" },
]

[[modules]]
path = "pare.cli"
depends_on = [
    { path = "pare.client" },
    { path = "pare.console" },
    { path = "pare.constants" },
    { path = "pare.login" },
    { path = "pare.models" },
    { path = "pare.settings" },
]

[[modules]]
path = "pare.client"
depends_on = [
    { path = "pare.console" },
    { path = "pare.settings" },
]

[[modules]]
path = "pare.console"
depends_on = []

[[modules]]
path = "pare.constants"
depends_on = []

[[modules]]
path = "pare.errors"
depends_on = []

[[modules]]
path = "pare.login"
depends_on = [
    { path = "pare.console" },
    { path = "pare.constants" },
    { path = "pare.settings" },
]

[[modules]]
path = "pare.models"
depends_on = []

[[modules]]
path = "pare.sdk"
depends_on = [
    { path = "pare.client" },
    { path = "pare.errors" },
    { path = "pare.models" },
    { path = "pare.settings" },
]

[[modules]]
path = "pare.settings"
depends_on = []
